# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Invoke deployment hook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: ${{ 'https://cd7d-2405-201-2024-580c-302a-ff1d-b989-e086.ngrok.io/api/testwebhook' }}
        webhook_secret: ${{ "fjhglhgouyfu" }}
        data: '{ "weapon": "hammer", "drink" : "beer" }'
